// FAKE DATA
export const products = [
  {
    id: 1,
    title: "Kinder Happy Hippo Hazelnut",
    url: "https://www.worldofsnacks.com/uploads/1/3/1/2/13127180/s643667121527569464_p666_i2_w810.jpeg",
    originalPrice: 1.5,
    salePrice: 1.35,
    description:
      "A fun wafer cookies shaped like a hippo, this is our favorite animal shaped biscuit from anywhere in the world!  Inside this crunch snack is two layers of sweet icing, one chocolate and the other milk.  As if that wasn't enough- the bottom of the cookie is then dipped in chocolate and flaked with little crunchy bits.  Order the Happy Hippo and other Kinder cookies online now!",
    country: "Germany",
    type: "cookie",
  },
  {
    id: 2,
    title: "Bourbon Choco and Coffee Biscuits",
    url: "https://www.worldofsnacks.com/uploads/1/3/1/2/13127180/s643667121527569464_p355_i3_w1000.jpeg",
    originalPrice: 4,
    salePrice: 3.6,
    description:
      "A tasty shortbread cookie with creamy coffee flavor filling, the Bourbon Choco & Coffee Biscuits are a much-loved high-end cookie that we import directly from Japan.  Now you can have these Japanese Biscuits delivered anywhere in the world with international shipping from our US based snack store.  Order online now and be sure to come back and tell us how much you love them!",
    country: "Japan",
    type: "cookie",
  },
  {
    id: 3,
    title: "Burtons Jammie Dodgers",
    url: "https://www.worldofsnacks.com/uploads/1/3/1/2/13127180/s643667121527569464_p48_i2_w600.jpeg",
    originalPrice: 3.75,
    salePrice: 3.43,
    description:
      "By popular demand we have recently expanded our offering of British Snacks to include Jammie Dodgers.  Manufactured by Burton’s Biscuit Company, Jammie Dodgers are one of the most popular children’s biscuits in England.  Although, you don’t have to be a kid to enjoy this treat!  These cookies style snacks are also famous; they have been featured in Doctor Who and many other British TV shows and movies!",
    country: "United Kingdom",
    type: "cookie",
  },
  {
    id: 4,
    title: "Magic Creams Butter Cracker Sandwich",
    url: "https://www.worldofsnacks.com/uploads/1/3/1/2/13127180/s643667121527569464_p237_i2_w1000.jpeg",
    originalPrice: 1.5,
    salePrice: 1.35,
    description:
      "Crackers from anywhere in the world always seem to taste better with butter.  Jack n' Jill Magic Creams are prebuttered cracker sandwiches imported from the Philippines for sale here in the US with shipping across the globe.  You can now order Magic Creams and other Filipino Cracker Snacks online!",
    country: "Philippines",
    type: "cookie",
  },
  {
    id: 5,
    title: "Marinela Barritas Fresa",
    url: "https://www.worldofsnacks.com/uploads/1/3/1/2/13127180/s643667121527569464_p210_i2_w1000.jpeg",
    originalPrice: 4.0,
    salePrice: 3.6,
    description:
      "This Mexican Strawberry filled cookie produced by Marinela is the perfect combination of sweet fruit filling and soft crumbly cookie.  SnaxShop offer the Barritas Fresa and it’s counterpart the Barritas Pina for sale in the US with international shipping around the world.  Order these and other Mexican Snacks online now!     ",
    country: "Mexico",
    type: "cookie",
  },
  {
    id: 6,
    title: "SkyFlakes Condensada Cracker Sandwich",
    url: "https://www.worldofsnacks.com/uploads/1/3/1/2/13127180/s643667121527569464_p438_i3_w600.jpeg",
    originalPrice: 1.5,
    salePrice: 1.35,
    description:
      "Simple yet so tasty.  M.Y. San SkyFlakes Condensasa are cracker sandwiches filled with sweet condensed milk.  In many families around the world this is a classic snack.  Now offered in a ready to go format, this treat is sure to be a hit.  SnaxShop offers these and other Cracker Snacks from the Philippines for sale online.  We ship from our US based warehouse to anywhere in the world.  Order now!",
    country: "Philippines",
    type: "cookie",
  },
  {
    id: 7,
    title: "Parle Monaco Classic",
    url: "https://www.worldofsnacks.com/uploads/1/3/1/2/13127180/s643667121527569464_p831_i7_w750.jpeg",
    originalPrice: 1.5,
    salePrice: 1.35,
    description:
      "The Ritz Crackers of India, except better!  This simple imported snack acts as the perfect backdrop for toppings or are equally enjoyable by themselves.  SnaxShop offers Parle Monaco Classic Crackers for sale online here in the US with international shipping. No matter where you live you can enjoy this yummy snack!",
    country: "India",
    type: "cookie",
  },
  {
    id: 8,
    title: "Gilco Pocky Cookies and Cream",
    url: "https://www.worldofsnacks.com/uploads/1/3/1/2/13127180/s643667121527569464_p762_i11_w750.jpeg",
    originalPrice: 4,
    salePrice: 3.6,
    description: "Hands down our favorite cookies from Thailand - Pocky Cookies & Cream are simply awesome.  Your are going to love these Cookies and Cream covered biscuits sticks.  Best of all, SnaxShop stocks them here in the US and offers worldwide shipping!  Be sure to order these and some of the other amazing Pocky flavors.",
    country: "Thailand",
    type: "cookie",
  },
  {
    id: 9,
    title: "Ulker Biskrem",
    url: "https://www.worldofsnacks.com/uploads/1/3/1/2/13127180/s643667121527569464_p455_i6_w647.jpeg",
    originalPrice: 3.5,
    salePrice: 3.15,
    description: "A decadent treat imported from Turkey, Ulker Biskrem are crunchy gourmet cookies filled with Cocoa Cream.  SnaxShop now offers a range of Ulker snacks imported from Turkey for sale online.  We also offer international shipping from our US based warehouse to nearly everywhere on the planet.  Now no matter where you live you can enjoy Ulker Biskrem Cookies!    ",
    country: "Turkey",
    type: "cookie",
  },
  {
    id: 10,
    title: "Lotte Koala's March Strawberry",
    url: "https://www.worldofsnacks.com/uploads/1/3/1/2/13127180/s643667121527569464_p1011_i10_w750.jpeg",
    originalPrice: 2.5,
    salePrice: 2.25,
    description: "Limited edition cookies with fun Koala characters filled with strawberry cream – what's not to love?  SnaxShop sells a vast selection of cookies and Lotte Koala's March Strawberry is our newest offering.  Order these cookies here online in the United States and have them shipped to you anywhere in the world.",
    country: "Thailand",
    type: "cookie",
  },
  {
    id: 11,
    title: "Lotte Koala's March Chocolate",
    url: "https://www.worldofsnacks.com/uploads/1/3/1/2/13127180/s643667121527569464_p1012_i11_w750.jpeg",
    originalPrice: 2.5,
    salePrice: 2.25,
    description: "The most adorable cookies we sell, Lotte Koala's Match Chocolate Biscuits are super fun to eat and are quite yummy.  The crunch cookie shell features unique Koala Bear art and inside you will find rich chocolate cream.  You can order these and other tasty Koala's March flavors for sale here online in the USA with worldwide shipping to everywhere.",
    country: "Thailand",
    type: "cookie",
  },
  {
    id: 12,
    title: "Hapi Bing Bing Chocolate",
    url: "https://www.worldofsnacks.com/uploads/1/3/1/2/13127180/s643667121527569464_p1066_i8_w750.jpeg",
    originalPrice: 6,
    salePrice: 5.4,
    description: null,
    country: "Korea",
    type: "cookie",
  },
  {
    id: 13,
    title: "CaramBar Caramel L'original",
    url: "https://www.worldofsnacks.com/uploads/1/3/1/2/13127180/s643667121527569464_p885_i9_w750.jpeg",
    originalPrice: 1.50,
    salePrice: 1.35,
    description: "Our first French candy has arrived and it's a good one!  CaramBar is a classic in France and soon to be loved here in the United States and around the world.  It's part American Sugar Daddy and Tootsie Role.  CaramBar Caramel is a 4 inch long stick that is soft when warm and hard when cold, and no matter how consumed it's always tasty.  SnaxShop offers CaramBar Caramel L'original for sale here online in the US with international shipping around the globe. Order now!",
    country: "France",
    type: "candy",
  },
  {
    id: 14,
    title: "Perugina Rossana",
    url: "https://www.worldofsnacks.com/uploads/1/3/1/2/13127180/s643667121527569464_p870_i6_w600.jpeg",
    originalPrice: 1.5,
    salePrice: 1.35,
    description: "A divine candy treat from Italy, the Perugina Rossana is a the prefect balance between flavors that include almonds and hazelnut and a creamy milk center.  SnaxShop offers this much loved Italian treat for sale in the US with international shipping around the world.  Order online now and enjoy the taste of Italy!",
    country: "Italy",
    type: "candy",
  },
  {
    id: 15,
    title: "Rowntrees Fruit Gums",
    url: "https://www.worldofsnacks.com/uploads/1/3/1/2/13127180/s643667121527569464_p99_i3_w1146.jpeg",
    originalPrice: 2,
    salePrice: 1.8,
    description: "Delicious chewy fruit flavored gummies directly from England!  SnaxShop has just expanded our British Candy inventory to include Rowntree Fruit Gums.  Produced by Nestle and made with no artificial colors or flavors this sweet treat is sure to be a hit with the whole family!",
    country: "United Kingdom",
    type: "candy",
  },
  {
    id: 16,
    title: "Rowntrees Fruit Pastilles",
    url: "https://www.worldofsnacks.com/uploads/1/3/1/2/13127180/s643667121527569464_p100_i2_w657.jpeg",
    originalPrice: 2.5,
    salePrice: 2.25,
    description: "SnaxShop stocks this long time British snack favorite!  Nestle Rowntree Fruit Pastilles are chewy sugar coated candies that are made with real fruit flavors.  Imported directly from the UK and shipped around the world, our company offers these tasty sweets as well as the Rowntree Fruit Gums.  Order them both online now!",
    country: "United Kingdom",
    type: "candy",
  },
  {
    id: 17,
    title: "Haribo Rasberries Gummi Candy",
    url: "https://www.worldofsnacks.com/uploads/1/3/1/2/13127180/s643667121527569464_p158_i1_w563.jpeg",
    originalPrice: 2.5,
    salePrice: 2.25,
    description: null,
    country: "Germany",
    type: "candy",
  },
  {
    id: 18,
    title: "Limon 7",
    url: "https://www.worldofsnacks.com/uploads/1/3/1/2/13127180/s643667121527569464_p187_i2_w695.jpeg",
    originalPrice: 1.5,
    salePrice: 1.35,
    description: "This snack from Mexico can be consumed on its own but it is also great on other snacks or even in drinks!  Limon Salt & Lemon Powder is a tangy treat that you can now order online. SnaxShop offers Limon 7 for sale online here in the USA with international shipping available.",
    country: "Mexico",
    type: "candy",
  },
  {
    id: 19,
    title: "XO Classics Coffee Candy",
    url: "https://www.worldofsnacks.com/uploads/1/3/1/2/13127180/s643667121527569464_p240_i1_w1000.jpeg",
    originalPrice: 3,
    salePrice: 2.7,
    description: "A perfect blend of the best ingredients, Jack n' Jill X.O. Classics Coffee Candy is an extraordinary coffee experience!  SnaxShop offers this delicious Filipino snack and many others for sale online here in the US with international shipping around the world.  Order your international candy today!",
    country: "Philippines",
    type: "candy",
  },
  {
    id: 20,
    title: "Chocolate Curly Tops",
    url: "https://www.worldofsnacks.com/uploads/1/3/1/2/13127180/s643667121527569464_p281_i1_w1000.jpeg",
    originalPrice: 5,
    salePrice: 4.5,
    description: "A unique take on chocolate, Ricoa Curly Tops do not contain any Cocoa butter and do not melt in heat.  However this Filipino candy does dissolve in your mouth. The chocolate is a bit waxy but a must sample for any serious chocolate or international snack enthusiasts.  SnaxShop offers a variety of chocolate treats from around the world.  Order online now and we will ship your snacks from our US based warehouse to anywhere in the world!",
    country: "Philippines",
    type: "candy",
  },
  {
    id: 21,
    title: "Vero Elotes Lollipop",
    url: "https://www.worldofsnacks.com/uploads/1/3/1/2/13127180/s643667121527569464_p291_i2_w753.jpeg",
    originalPrice: 1.5,
    salePrice: 1.35,
    description: "Searching for a foreign snack you've never tried?  Chances are the average snack lover has yet to try Vero Elotes Lollipops. This unique flavor is a blend of grilled corn and strawberry, covered in chili powder!  It's spicy but not overpowering and pleasantly sweet.  Order the Vero Elotes or the Vero Mango here online with SnaxShop and have them shipped to you anywhere!",
    country: "Mexico",
    type: "candy",
  },
  {
    id: 22,
    title: "Haitai Sweet Redbean Jelly Bar",
    url: "https://www.worldofsnacks.com/uploads/1/3/1/2/13127180/s643667121527569464_p308_i1_w425.jpeg",
    originalPrice: 2,
    salePrice: 1.8,
    description: "In Japan this snack is known as 'Yokan' which is simply Jellied Red Bean Paste.  Haitai Sweet Redbean Jelly Bars come in a sweet fudge like consistency and they are pleasantly sweet with just the right amount of Red Bean undertones.  SnaxShop offers the Haitai Sweet Redbean Jelly Bars and other Korean Candies for sale online in the US with shipping around the world. Order now!",
    country: "Korea",
    type: "candy",
  },
  {
    id: 23,
    title: "Langka Jackfruit Candy",
    url: "https://www.worldofsnacks.com/uploads/1/3/1/2/13127180/s643667121527569464_p440_i2_w500.jpeg",
    originalPrice: 1.5,
    salePrice: 1.35,
    description: "Sweet and delicious, this Filipino Candy is chewy and get a tad grainy toward the end.  It's easy to see why this is a much loved snack from the Philippines!  SnaxShop now offers Langka Jackfruit Candy for sale here in the US with international shipping.  Be sure to order enough to share.",
    country: "Philippines",
    type: "candy",
  },
  {
    id: 24,
    title: "Korivka Roshen",
    url: "https://www.worldofsnacks.com/uploads/1/3/1/2/13127180/s643667121527569464_p497_i3_w681.jpeg",
    originalPrice: 1.5,
    salePrice: 1.35,
    description: "It's finally here!  SnaxShop has tracked down the famous 'Candy Cow' from Ukraine.  Roshen says the Korivka is unglazed sweets with a milk fondant center and covered in sugar.  We say it's soft, sweet, delicious - and you are going to love it!  You can now order Korivka Roshen (Candy Cow) here online and have it shipped from our US based snack store to anywhere in the world!",
    country: "Ukraine",
    type: "candy",
  },
  {
    id: 25,
    title: "Lucky Me Beef na Beef",
    url: "https://www.worldofsnacks.com/uploads/1/3/1/2/13127180/s643667121527569464_p596_i4_w750.jpeg",
    originalPrice: 1.5,
    salePrice: 1.35,
    description: "Instant noodles with beef flavor are a classic.  Tons of snack companies from around the world offer this easy to make snack.  However, no one does it better than Lucky Me!  They provide more than just a seasoning packet.  You get enough ingredients to create a dish that tastes fresh and it's bursting with stewed beef flavor.  Now is a great time to order Lucky Me Beef na Beef and have it shipped from our US based snack store to anywhere in the world.",
    country: "Philippines",
    type: "noodles",
  },
  {
    id: 26,
    title: "Lucky Me Pancit Canton",
    url: "https://www.worldofsnacks.com/uploads/1/3/1/2/13127180/s643667121527569464_p597_i6_w750.jpeg",
    originalPrice: 1.5,
    salePrice: 1.35,
    description: "So simple, yet so enjoyable.  The Luck Me Pancit Canton Citrus is a thick, buttery noodle dish that is accented by a blast of citrus flavor.  Best of all, it's an instant noodle, so it's nearly effortless to make this snack and you won't believe how great they taste with such a low price. SnaxShop now offers a large selection of Filipino Noodles.  You can purchase them here online and have them shipped from our US based snack store to anywhere in the world!",
    country: "Philippines",
    type: "noodles",
  },
  {
    id: 27,
    title: "Lucky Me Pancit Canton Extra Hot Chili",
    url: "https://www.worldofsnacks.com/uploads/1/3/1/2/13127180/s643667121527569464_p598_i6_w750.jpeg",
    originalPrice: 1.5,
    salePrice: 1.35,
    description: "If you love spicy food like we do, you are going to really enjoy the Lucky Me Pancit Canton Extra Hot Chili Noodles.  So what is Pancit Canton?  Well, it's the Filipino version of Chow Mein.  Large noodles with a firm texture, they are a real treat.  Order these online now and enjoy the buttery spicy goodness of this snack from the Philippines. SnaxShop ships Lucky Me Pancit Canton Extra Hot Chili Noodles from our snack store here in the US to anywhere in the world.   Order now!",
    country: "Philippines",
    type: "noodles",
  },
  {
    id: 28,
    title: "Lucky Me Pancit Canton Chili Citrus",
    url: "https://www.worldofsnacks.com/uploads/1/3/1/2/13127180/s643667121527569464_p600_i7_w750.jpeg",
    originalPrice: 1.5,
    salePrice: 1.35,
    description: "Pancit, or Filipino Birthday noodles are similar to chow mein. They are thicker and chewier than typical instant noodles. This version, the Lucky Me Pancit Canton Chili & Citrus is one of our favorites.  The noodles are the perfect consistency and the buttery chili & citrus flavor packs a little heat and a lot of yummy flavor.  SnaxShop now offers a large selection of Filipino Noodles for sale online with shipping from our US based snack store to anywhere in the world.",
    country: "Philippines",
    type: "noodles",
  },
  {
    id: 29,
    title: "Lucky Me Chicken na Chicken",
    url: "https://www.worldofsnacks.com/uploads/1/3/1/2/13127180/s643667121527569464_p601_i5_w750.jpeg",
    originalPrice: 1.5,
    salePrice: 1.35,
    description: "SnaxShop has expanded to offer a varied selection of Filipino Noodles. Lucky Me! is the most loved producer of instant noodles in the Philippines and the Chicken Na Chicken flavor is one of the best sellers.  So much more than American Ramen noodles, this snack is a real treat.  Enjoy noodles that are the perfect texture with a stewed chicken flavor that is so tasty.  Order the Lucky Me Chicken na Chicken here online and have it shipped from our warehouse in the US to anywhere on the globe.",
    country: "Philippines",
    type: "noodles",
  },
  {
    id: 30,
    title: "Ottogi Ppushu Ppushu BBQ Flavor",
    url: "https://www.worldofsnacks.com/uploads/1/3/1/2/13127180/s643667121527569464_p422_i4_w573.jpeg",
    originalPrice: 2.5,
    salePrice: 1.35,
    description: "We love smashing a great snack.  No for real, that is the best way to eat Ottogi Ppushu Ppushu BBQ Flavor Noodle Snack.  Before you open the bag, you crush the contents into small pieces.  The result is a snack similar to Ramen, except there is no need to cook it.  The BBQ Flavor is zesty and very enjoyable. SnaxShop now offers a range of snacks from Korea for sale online.  You can order them here on our site and have them shipped to you from our US based warehouse to anywhere in the world!    ",
    country: "Korea",
    type: "noodles",
  },
  {
    id: 31,
    title: "Ottogi Ppushu Ppushi Spicy Rice",
    url: "https://www.worldofsnacks.com/uploads/1/3/1/2/13127180/s643667121527569464_p961_i7_w634.jpeg",
    originalPrice: 2.5,
    salePrice: 1.35,
    description: "So yummy, the Ottogi Ppushu Ppushu Spicy Rice Flavored Noodle Snack is awesome.  It's crunchy noodles that you don't bother boiling tossed in spicy rice cake flavor. Fun to eat and easy to share!  SnaxShop offers this Korean Snack for sale online in the US with international shipping. Order online right this second!",
    country: "Korea",
    type: "noodles",
  },
  {
    id: 32,
    title: "Samyang Hot Chicken 2X Spicy Ramen",
    url: "https://www.worldofsnacks.com/uploads/1/3/1/2/13127180/s643667121527569464_p1064_i9_w750.jpeg",
    originalPrice: 2.75,
    salePrice: 1.35,
    description: null,
    country: "Korea",
    type: "noodles",
  },
  {
    id: 33,
    title: "Samyang Buldak Kimchi Hot Chicken Flavor Ramen",
    url: "https://www.worldofsnacks.com/uploads/1/3/1/2/13127180/s643667121527569464_p1142_i10_w378.jpeg",
    originalPrice: 2.75,
    salePrice: 1.35,
    description: null,
    country: "Korea",
    type: "noodles",
  },
];
